### PR TITLE
Added Dev-Requirements file

### PR DESCRIPTION
**Pull request by JayKayAce**
I was setting up the development environment and was missing a requirements file for all the packages needed to get the code up and running. 
I think this should cover it.
I added pytest and black to the installation environment for good measure.
Best regards
JayKayAce
(JKS on Pythonista Cafe)

### CODE REVIEW

**Comment by PFython** [comment]
Just double checking as I have no experience with this Jesper... it looks like you've added a Binary file but I thought requirements.txt needs to actually be a plain text file?

**Comment by JayKayAce** [comment]
For the life of me, I do not understand why git treats my file as a binary file when running "pip freeze > requirements.txt" it should just be a normal text file.

**Comment by JayKayAce** [comment]
I tried as a last resort to read the file in python and here it riddled with null characters and some funny starting characters. That might be the culprit

**Comment by JayKayAce** [comment]
I will post a question on the Pythonista forum this weekend regarding this, I am sure someone has come across this.

**Comment by JayKayAce** [comment]
Closing PR for now.

**Pull request closed without merging**
